#!/usr/bin/env python3
"""make_chair_scene.py — build a MuJoCo sim scene containing a chair, from the
`sit_evalset` / `sit_demo` environment descriptors in `~/ego_dataset/`.

Why this exists
---------------
`~/ego_dataset/sit_evalset/envs/<clip>.json` records, per sitting clip, the seat
geometry that the motion was retargeted against:

    seat_center : [x, y, z]   centre of the seat TOP surface, world frame
    seat_yaw    : radians     rotation about +Z
    seat_size   : [sx, sy, sz] full extents of the seat slab (m)
    kinematic   : true        the chair never moves

The asset itself (`chair_seat.usda`) is a single box, so it maps onto a MuJoCo
`type="box"` geom exactly -- no mesh conversion needed. MuJoCo box `size` is the
HALF-extent, and the geom origin is the box CENTRE, whereas `seat_center` is the
centre of the TOP face, hence the `-sz/2` shift applied below.

The chair is emitted as a **static** geom (a worldbody child with no joint), which
matches `kinematic: true`: the robot can sit on it and it will not move or fall over.

Usage
-----
    # list the available sitting clips + their seat geometry
    .venv_sim/bin/python data_process/make_chair_scene.py --list

    # generate a scene for one clip (seat height taken from the clip)
    .venv_sim/bin/python data_process/make_chair_scene.py \
        --clip sit_on_chair_loop_R_001__A248

    # override the seat height (metres, top surface) -> auto-named variant
    .venv_sim/bin/python data_process/make_chair_scene.py \
        --clip sit_on_chair_loop_R_001__A248 --seat-height 0.45

    # generate a whole set of heights at once
    .venv_sim/bin/python data_process/make_chair_scene.py \
        --clip sit_on_chair_loop_R_001__A248 --seat-heights 0.30 0.37 0.43 0.50

    # ... then launch the sim against one of them
    env -u CYCLONEDDS_HOME .venv_sim/bin/python gear_sonic/scripts/run_sim_loop.py \
        --wbc-version sonic_model12_chair_h45

Seat height notes
-----------------
The clip-derived heights are all ~0.365-0.408 m, which is what the *human*
performer sat on (`pelvis_z_seated` ~0.466 m). The G1's pelvis at default angles
is 0.722 m above the ankle links and its leg proportions differ, so the
clip-native height is not necessarily the right height for the robot -- hence
the override.
"""
import argparse
import glob
import json
import math
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL_DIR = os.path.join(REPO, "gear_sonic/data/robot_model/model_data/g1")
WBC_DIR = os.path.join(REPO, "gear_sonic/utils/mujoco_sim/wbc_configs")
DEFAULT_ENVS = [
    os.path.expanduser("~/ego_dataset/sit_evalset/envs"),
    os.path.expanduser("~/ego_dataset/sit_demo/envs"),
]

SCENE_TEMPLATE = """<mujoco model="g1_43dof scene + chair">
  <!-- GENERATED by data_process/make_chair_scene.py. Do not edit by hand.
       NOTE: a double hyphen is illegal inside an XML comment, so avoid it here.
       clip:        {clip}
       source:      {json_path}
       seat_center: {seat_center}  (centre of seat TOP surface)
       seat_yaw:    {seat_yaw} rad
       seat_size:   {seat_size}  (full extents)
  -->
  <include file="g1_29dof_with_hand.xml"/>

  <statistic center="0 0 0.5" extent="2.0"/>

  <visual>
    <headlight diffuse="0.6 0.6 0.6" ambient="0.3 0.3 0.3" specular="0 0 0"/>
    <rgba haze="0.15 0.25 0.35 1"/>
    <global azimuth="-130" elevation="-20"/>
  </visual>

  <asset>
    <texture type="skybox" builtin="gradient" rgb1="0.3 0.5 0.7" rgb2="0 0 0" width="512" height="3072"/>
    <texture type="2d" name="groundplane" builtin="checker" mark="edge" rgb1="0.2 0.3 0.4" rgb2="0.1 0.2 0.3"
      markrgb="0.8 0.8 0.8" width="300" height="300"/>
    <material name="groundplane" texture="groundplane" texuniform="true" texrepeat="5 5" reflectance="0.2"/>
    <material name="chair_mat" rgba="0.45 0.30 0.20 1"/>
  </asset>

  <worldbody>
    <light pos="0 0 1.5" dir="0 0 -1" directional="true"/>
    <geom name="floor" size="0 0 0.05" type="plane" material="groundplane"/>
    <!-- Site -->
    <site name="com_marker" pos="0.1 0 0" size="0.05" rgba="1 0 0 1" type="sphere"/>

    <!-- Chair: static (no joint), i.e. kinematic, matching chair_seat.usda -->
    <!-- mocap="true": still immovable by contact, but the sim can teleport it
         (press 'c' in the sim to respawn it under the robot). -->
    <body name="chair_body" mocap="true" pos="{cx} {cy} {cz}" euler="0 0 {yaw}">
      <geom name="chair_seat" type="box" size="{hx} {hy} {hz}" material="chair_mat"
            friction="1.0 0.005 0.0001" solimp="0.998 0.998 0.001"/>
{legs}    </body>
  </worldbody>

  <default>
    <geom friction="1.0"/>
  </default>
</mujoco>
"""

LEG_TEMPLATE = ('      <geom name="chair_leg_{i}" type="box" pos="{x} {y} {z}" '
                'size="{r} {r} {h}" material="chair_mat"/>\n')

WBC_TEMPLATE = """# GENERATED by data_process/make_chair_scene.py for clip: {clip}
# Copy of g1_29dof_sonic_model12.yaml with ROBOT_SCENE pointed at the chair scene.
{body}"""


def load_envs(env_dirs):
    out = {}
    for d in env_dirs:
        for p in sorted(glob.glob(os.path.join(d, "*.json"))):
            with open(p) as fh:
                try:
                    j = json.load(fh)
                except json.JSONDecodeError:
                    continue
            if "seat_center" in j:
                j["_path"] = p
                out[j.get("clip", os.path.basename(p)[:-5])] = j
    return out


def build_scene(env, with_legs=True, seat_height=None, seat_xy=None,
                distance=None, bearing_deg=0.0):
    cx, cy, cz = env["seat_center"]
    sx, sy, sz = env["seat_size"]
    if seat_height is not None:
        cz = float(seat_height)          # z of the seat TOP surface
    yaw = float(env.get("seat_yaw", 0.0))

    # Placement. The clip-native seat centre sits at the motion's own origin,
    # which coincides with the robot spawn (0, 0, 0.793) -- the chair would be
    # inside the robot. Offset it unless the caller asks otherwise.
    if seat_xy is not None:
        cx, cy = float(seat_xy[0]), float(seat_xy[1])
    elif distance is not None:
        b = math.radians(bearing_deg)
        cx, cy = distance * math.cos(b), distance * math.sin(b)
        # Face the seat back toward the robot so it can back up and sit down.
        yaw = b
    hx, hy, hz = sx / 2.0, sy / 2.0, sz / 2.0
    # seat_center is the TOP face; MuJoCo box origin is the centre.
    cz_geom = cz - hz

    legs = ""
    if with_legs:
        # Purely cosmetic: the seat slab alone would float. Legs run from the
        # ground to the underside of the slab, inset from the seat corners.
        leg_r = 0.025
        leg_h = max(0.01, (cz - sz) / 2.0)
        inset = 0.04
        for i, (sgn_x, sgn_y) in enumerate([(1, 1), (1, -1), (-1, 1), (-1, -1)]):
            legs += LEG_TEMPLATE.format(
                i=i, r=leg_r, h=leg_h,
                x=round(sgn_x * (hx - inset - leg_r), 4),
                y=round(sgn_y * (hy - inset - leg_r), 4),
                z=round(-hz - leg_h, 4),
            )

    return SCENE_TEMPLATE.format(
        clip=env.get("clip", "?"), json_path=env["_path"],
        seat_center=[cx, cy, cz], seat_yaw=yaw, seat_size=env["seat_size"],
        cx=round(cx, 4), cy=round(cy, 4), cz=round(cz_geom, 4), yaw=round(yaw, 6),
        hx=round(hx, 4), hy=round(hy, 4), hz=round(hz, 4), legs=legs,
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--clip", help="clip name, e.g. sit_on_chair_loop_R_001__A248")
    ap.add_argument("--env-dirs", nargs="*", default=DEFAULT_ENVS)
    ap.add_argument("--list", action="store_true", help="list available clips and exit")
    ap.add_argument("--scene-name", default=None,
                    help="override the generated scene filename")
    ap.add_argument("--wbc-name", default=None,
                    help="override the generated wbc yaml filename")
    ap.add_argument("--seat-height", type=float, default=None,
                    help="override the seat TOP-surface height in metres")
    ap.add_argument("--seat-heights", type=float, nargs="*", default=None,
                    help="generate one scene+yaml per height (metres)")
    ap.add_argument("--distance", type=float, default=1.0,
                    help="place the chair this far from the robot spawn (0,0), in "
                         "metres. Default 1.0; the clip-native seat position "
                         "coincides with the spawn, so the chair would otherwise be "
                         "inside the robot.")
    ap.add_argument("--bearing", type=float, default=0.0,
                    help="direction to the chair in degrees, 0 = +x (in front)")
    ap.add_argument("--seat-xy", type=float, nargs=2, default=None,
                    help="explicit seat centre x y, overrides --distance/--bearing")
    ap.add_argument("--keep-clip-xy", action="store_true",
                    help="use the clip's own seat x/y (overlaps the robot spawn)")
    ap.add_argument("--no-legs", action="store_true",
                    help="emit only the seat slab (no cosmetic legs)")
    args = ap.parse_args()

    envs = load_envs(args.env_dirs)
    if args.list or not args.clip:
        print(f"{len(envs)} sitting environments found:\n")
        print(f"{'clip':50s} {'seat_center':28s} {'yaw':>8s}  seat_size")
        for name, e in sorted(envs.items()):
            c = [round(v, 3) for v in e['seat_center']]
            print(f"{name:50s} {str(c):28s} {e.get('seat_yaw', 0):8.3f}  {e['seat_size']}")
        if not args.clip:
            print("\nPass --clip <name> to generate a scene.")
        return

    if args.clip not in envs:
        raise SystemExit(f"clip {args.clip!r} not found; use --list")
    env = envs[args.clip]

    heights = args.seat_heights or [args.seat_height]
    versions = []
    for h in heights:
        # h=None -> use the clip's own height, and the unsuffixed names.
        suffix = "" if h is None else f"_h{int(round(float(h) * 100)):02d}"
        scene_name = args.scene_name or f"scene_43dof_chair{suffix}.xml"
        wbc_name = args.wbc_name or f"g1_29dof_sonic_model12_chair{suffix}.yaml"

        scene_path = os.path.join(MODEL_DIR, scene_name)
        with open(scene_path, "w") as fh:
            fh.write(build_scene(env, with_legs=not args.no_legs, seat_height=h,
                                 seat_xy=args.seat_xy,
                                 distance=None if args.keep_clip_xy else args.distance,
                                 bearing_deg=args.bearing))
        eff_h = env["seat_center"][2] if h is None else float(h)
        if args.seat_xy is not None:
            place = f"xy=({args.seat_xy[0]:.2f}, {args.seat_xy[1]:.2f})"
        elif args.keep_clip_xy:
            place = (f"xy=({env['seat_center'][0]:.3f}, {env['seat_center'][1]:.3f}) "
                     f"clip-native, OVERLAPS robot spawn")
        else:
            place = f"{args.distance:.2f} m @ {args.bearing:.0f} deg from spawn"
        print(f"[scene] {scene_path}")
        print(f"        seat top z={eff_h:.4f} m  {place}  size={env['seat_size']}"
              + ("  (clip height)" if h is None else "  (height overridden)"))

        # Mirror the stock wbc yaml with ROBOT_SCENE repointed.
        src = os.path.join(WBC_DIR, "g1_29dof_sonic_model12.yaml")
        with open(src) as fh:
            body = fh.read()
        rel = f"gear_sonic/data/robot_model/model_data/g1/{scene_name}"
        out_lines = []
        for line in body.splitlines(True):
            if line.strip().startswith("ROBOT_SCENE:"):
                line = (f'ROBOT_SCENE: "{rel}" # chair scene, {args.clip}, '
                        f'seat top {eff_h:.3f} m\n')
            out_lines.append(line)
        wbc_path = os.path.join(WBC_DIR, wbc_name)
        with open(wbc_path, "w") as fh:
            fh.write(WBC_TEMPLATE.format(clip=args.clip, body="".join(out_lines)))
        print(f"[wbc]   {wbc_path}")
        versions.append(os.path.basename(wbc_name)[len("g1_29dof_"):-len(".yaml")])

    print(f"\nEnsure these are in WBC_VERSIONS (gear_sonic/utils/mujoco_sim/configs.py):")
    print("  " + ", ".join(repr(v) for v in versions))
    print("\nRun with, e.g.:\n"
          f"  env -u CYCLONEDDS_HOME .venv_sim/bin/python "
          f"gear_sonic/scripts/run_sim_loop.py --wbc-version {versions[0]}")


if __name__ == "__main__":
    main()
