#!/usr/bin/env python3
"""Per-clip failure second on ICL_hardset (single-attempt evals).

failure second = progress * clip duration, where progress is the fraction of the clip's frames completed before
the tracking termination fired (progress 1.0 / terminated=0 => no failure). Duration = robot frames / 30 fps.

Outputs: sim2real/icl_hard_set/icl_failure_seconds.csv and sim2real/icl_failure_seconds.md
Usage:   python sim2real/icl_failure_seconds.py
"""
import csv
import glob
import json
import os

import numpy as np

LOGS = os.path.expanduser("~/GR00T-WholeBodyControl/logs_eval")
HERE = os.path.dirname(os.path.abspath(__file__))
RUNS = ["base100k", "mixv3b_010000", "mixv3b_014000", "mixv3b_020000"]
man = {c["name"]: c for c in json.load(open(os.path.expanduser("~/ego_dataset/ICL_hardset/manifest.json")))["clips"]}


def load(tag):
    for d in sorted(glob.glob(f"{LOGS}/*EVAL_icl_{tag}"), reverse=True):
        try:
            return json.load(open(d + "/metrics_eval.json"))["eval/all_metrics_dict"]
        except Exception:
            continue


res = {}
for t in RUNS:
    a = load(t)
    if a:
        res[t] = {n: (int(a["terminated"][i]), float(a["progress"][i])) for i, n in enumerate(a["motion_keys"])}
runs = list(res)
rows = []
for n, c in man.items():
    dur = c["robot_frames"] / 30.0
    r = {"clip": n, "source": c["source"], "split": c["split"], "duration_s": round(dur, 2)}
    secs = []
    for t in runs:
        term, prog = res[t].get(n, (None, None))
        s = None if term is None else (round(prog * dur, 2) if term else None)
        r[f"fail_s_{t}"] = "" if term is None else ("ok" if not term else s)
        if s is not None:
            secs.append(s)
    r["n_runs_failed"] = len(secs)
    r["fail_s_min"] = round(min(secs), 2) if secs else ""
    r["fail_s_median"] = round(float(np.median(secs)), 2) if secs else ""
    rows.append(r)
rows.sort(key=lambda r: (r["fail_s_median"] == "", r["fail_s_median"] if r["fail_s_median"] != "" else 0))
cols = ["clip", "source", "split", "duration_s"] + [f"fail_s_{t}" for t in runs] + ["n_runs_failed", "fail_s_min", "fail_s_median"]
os.makedirs(f"{HERE}/icl_hard_set", exist_ok=True)
with open(f"{HERE}/icl_hard_set/icl_failure_seconds.csv", "w", newline="") as fh:
    w = csv.DictWriter(fh, fieldnames=cols)
    w.writeheader()
    w.writerows(rows)

with open(f"{HERE}/icl_failure_seconds.md", "w") as fh:
    fh.write("# ICL hard set: failure second per clip\n\n")
    fh.write("Single-attempt evals on `ICL_hardset` (35 clips). **Failure second = progress x clip duration** (progress is the fraction "
             "of frames completed before the tracking termination fired; `ok` = the clip ran to the end). Runs: "
             + ", ".join(f"`{t}`" for t in runs) + ". Sorted by median failure second; generated by `sim2real/icl_failure_seconds.py`.\n\n")
    fh.write("| clip | source | dur (s) | " + " | ".join(runs) + " | median fail (s) |\n|---|---|---|" + "---|" * (len(runs) + 1) + "\n")
    for r in rows:
        fh.write(f"| {r['clip'][:56]} | {r['source']} | {r['duration_s']} | "
                 + " | ".join(str(r[f'fail_s_{t}']) for t in runs) + f" | {r['fail_s_median'] if r['fail_s_median'] != '' else 'ok'} |\n")
    allf = [r["fail_s_median"] for r in rows if r["fail_s_median"] != ""]
    a = np.array(allf, dtype=float)
    fh.write(f"\n{len(a)} of {len(rows)} clips fail in at least one run. Median failure second over those clips: {np.median(a):.2f} s; "
             f"{(a < 0.5).sum()} fail before 0.5 s, {(a < 1).sum()} before 1 s, {(a < 2).sum()} before 2 s, {(a >= 2).sum()} at 2 s or later.\n")
print(f"{len(rows)} clips, {len(runs)} runs -> sim2real/icl_failure_seconds.md and icl_hard_set/icl_failure_seconds.csv")
print(f"failing clips: {len(a)}; <0.5 s: {(a < 0.5).sum()}  <1 s: {(a < 1).sum()}  <2 s: {(a < 2).sum()}  >=2 s: {(a >= 2).sum()}")
